"""填充演示数据，让网站在没有网络时也能看到效果。"""
from database import init_db, upsert_article
from datetime import datetime, timezone, timedelta

def seed():
    init_db()
    now = datetime.now(timezone.utc)

    demo_articles = [
        # Reuters
        {
            "source_id": "reuters_world",
            "source_name": "Reuters 路透社",
            "category": "权威媒体",
            "country": "美国/全球",
            "flag": "🌐",
            "color": "#FF6B35",
            "title": "G7 leaders agree on new framework for AI governance at summit",
            "summary": "Leaders of the Group of Seven nations reached a consensus on establishing a multilateral framework to regulate artificial intelligence development, focusing on safety standards and cross-border data flows.",
            "url": "https://www.reuters.com/article/g7-ai-summit",
            "published": (now - timedelta(minutes=15)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "reuters_world",
            "source_name": "Reuters 路透社",
            "category": "权威媒体",
            "country": "美国/全球",
            "flag": "🌐",
            "color": "#FF6B35",
            "title": "Global oil prices fall as OPEC+ signals supply increase",
            "summary": "Crude oil futures dropped more than 2% after OPEC+ members signaled a larger-than-expected production increase for the second half of the year, easing concerns about supply shortfalls.",
            "url": "https://www.reuters.com/article/opec-oil-supply",
            "published": (now - timedelta(hours=1)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # AP
        {
            "source_id": "ap_world",
            "source_name": "AP 美联社",
            "category": "权威媒体",
            "country": "美国/全球",
            "flag": "🇺🇸",
            "color": "#E63946",
            "title": "UN Security Council holds emergency session on regional tensions",
            "summary": "The United Nations Security Council convened an emergency meeting to address escalating regional tensions, with member states calling for immediate de-escalation and diplomatic dialogue.",
            "url": "https://apnews.com/article/un-security-council-emergency",
            "published": (now - timedelta(hours=2)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "ap_world",
            "source_name": "AP 美联社",
            "category": "权威媒体",
            "country": "美国/全球",
            "flag": "🇺🇸",
            "color": "#E63946",
            "title": "US economy grows at slower pace in Q1, Fed signals caution",
            "summary": "The US gross domestic product expanded at an annualized rate of 1.8% in the first quarter, below analyst expectations, as the Federal Reserve maintained its cautious stance on interest rate cuts.",
            "url": "https://apnews.com/article/us-gdp-q1-fed",
            "published": (now - timedelta(hours=3)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # BBC
        {
            "source_id": "bbc_world",
            "source_name": "BBC World",
            "category": "权威媒体",
            "country": "英国",
            "flag": "🇬🇧",
            "color": "#BB1919",
            "title": "Climate summit: Nations pledge deeper emissions cuts by 2035",
            "summary": "More than 80 countries signed a new climate pledge at the international summit, committing to reduce greenhouse gas emissions by at least 60% compared to 2019 levels before the end of the decade.",
            "url": "https://www.bbc.com/news/climate-summit-pledges",
            "published": (now - timedelta(hours=4)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "bbc_world",
            "source_name": "BBC World",
            "category": "权威媒体",
            "country": "英国",
            "flag": "🇬🇧",
            "color": "#BB1919",
            "title": "Ukraine conflict: Latest developments and ceasefire talks",
            "summary": "Diplomatic efforts to broker a ceasefire continue as both sides report ongoing military activity. International mediators held talks in Geneva aimed at establishing humanitarian corridors.",
            "url": "https://www.bbc.com/news/ukraine-conflict-latest",
            "published": (now - timedelta(hours=5)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # Al Jazeera
        {
            "source_id": "aljazeera",
            "source_name": "Al Jazeera 半岛电视台",
            "category": "权威媒体",
            "country": "卡塔尔",
            "flag": "🇶🇦",
            "color": "#E8721A",
            "title": "Middle East peace talks resume after months of stalemate",
            "summary": "Representatives from key stakeholders met in Doha to restart stalled negotiations, with mediators expressing cautious optimism about the prospects for a lasting agreement.",
            "url": "https://www.aljazeera.com/news/middle-east-peace-talks",
            "published": (now - timedelta(hours=6)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "aljazeera",
            "source_name": "Al Jazeera 半岛电视台",
            "category": "权威媒体",
            "country": "卡塔尔",
            "flag": "🇶🇦",
            "color": "#E8721A",
            "title": "Africa summit focuses on debt relief and infrastructure investment",
            "summary": "African Union leaders gathered to discuss strategies for sustainable debt management and attract foreign investment for critical infrastructure projects across the continent.",
            "url": "https://www.aljazeera.com/news/africa-summit-debt-relief",
            "published": (now - timedelta(hours=8)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # Xinhua
        {
            "source_id": "xinhua_en",
            "source_name": "Xinhua 新华社",
            "category": "官方媒体",
            "country": "中国",
            "flag": "🇨🇳",
            "color": "#CC0000",
            "title": "China's manufacturing sector expands for third consecutive month",
            "summary": "China's official Purchasing Managers' Index rose to 51.4 in April, indicating continued expansion in the manufacturing sector and signaling a stable economic recovery trajectory.",
            "url": "https://english.news.cn/manufacturing-pmi",
            "published": (now - timedelta(hours=2)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "xinhua_en",
            "source_name": "Xinhua 新华社",
            "category": "官方媒体",
            "country": "中国",
            "flag": "🇨🇳",
            "color": "#CC0000",
            "title": "China, ASEAN nations strengthen trade ties at annual forum",
            "summary": "Senior officials from China and the ten ASEAN member states met at the annual economic forum, signing agreements to expand trade, digital cooperation and green energy development.",
            "url": "https://english.news.cn/china-asean-forum",
            "published": (now - timedelta(hours=10)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # CGTN
        {
            "source_id": "cgtn",
            "source_name": "CGTN 中国国际电视台",
            "category": "官方媒体",
            "country": "中国",
            "flag": "🇨🇳",
            "color": "#8B0000",
            "title": "China launches next-generation satellite for global navigation",
            "summary": "The BeiDou-4 navigation satellite was successfully placed into orbit, further enhancing China's independent global navigation system and providing higher precision positioning services.",
            "url": "https://www.cgtn.com/story/beidou-satellite-launch",
            "published": (now - timedelta(hours=7)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # RT
        {
            "source_id": "rt_world",
            "source_name": "RT 今日俄罗斯",
            "category": "官方媒体",
            "country": "俄罗斯",
            "flag": "🇷🇺",
            "color": "#1A6FBF",
            "title": "Russia, China sign strategic cooperation agreements in Beijing",
            "summary": "Senior officials from Russia and China signed a series of bilateral agreements covering energy cooperation, infrastructure investment and scientific exchange during high-level talks in Beijing.",
            "url": "https://www.rt.com/russia/russia-china-agreements",
            "published": (now - timedelta(hours=9)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "rt_world",
            "source_name": "RT 今日俄罗斯",
            "category": "官方媒体",
            "country": "俄罗斯",
            "flag": "🇷🇺",
            "color": "#1A6FBF",
            "title": "Russia's Lavrov: Western sanctions policy is 'counterproductive'",
            "summary": "Russian Foreign Minister Sergei Lavrov stated at a press conference that Western economic sanctions have failed to achieve their stated objectives and are damaging global economic stability.",
            "url": "https://www.rt.com/russia/lavrov-sanctions-statement",
            "published": (now - timedelta(hours=11)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # DW
        {
            "source_id": "dw_world",
            "source_name": "Deutsche Welle 德国之声",
            "category": "官方媒体",
            "country": "德国",
            "flag": "🇩🇪",
            "color": "#C8161D",
            "title": "Germany unveils €50 billion industrial transformation fund",
            "summary": "The German government announced a major investment package to accelerate the transition of its industrial base toward renewable energy and green technology, targeting key manufacturing sectors.",
            "url": "https://www.dw.com/en/germany-industrial-fund",
            "published": (now - timedelta(hours=5)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # France 24
        {
            "source_id": "france24_en",
            "source_name": "France 24",
            "category": "官方媒体",
            "country": "法国",
            "flag": "🇫🇷",
            "color": "#003189",
            "title": "EU agrees new digital services regulation for tech platforms",
            "summary": "European Union member states reached final agreement on landmark digital services legislation requiring large technology platforms to increase transparency, content moderation and algorithmic accountability.",
            "url": "https://www.france24.com/en/eu-digital-services",
            "published": (now - timedelta(hours=6)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # NHK
        {
            "source_id": "nhk_world",
            "source_name": "NHK World 日本放送协会",
            "category": "官方媒体",
            "country": "日本",
            "flag": "🇯🇵",
            "color": "#003580",
            "title": "Japan's central bank keeps interest rates steady amid inflation concerns",
            "summary": "The Bank of Japan maintained its benchmark interest rate at 0.5% following its monetary policy meeting, citing continued uncertainty over domestic wage growth and global economic conditions.",
            "url": "https://www3.nhk.or.jp/nhkworld/en/boj-rates",
            "published": (now - timedelta(hours=12)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # UN
        {
            "source_id": "un_news",
            "source_name": "UN News 联合国新闻",
            "category": "国际组织",
            "country": "国际",
            "flag": "🌍",
            "color": "#009EDB",
            "title": "Secretary-General calls for urgent action on global food security",
            "summary": "UN Secretary-General urged world leaders to prioritize funding for food assistance programs as the number of people facing acute hunger surpasses 280 million, driven by conflict, climate change and economic instability.",
            "url": "https://news.un.org/en/story/food-security-urgent",
            "published": (now - timedelta(hours=3)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        {
            "source_id": "un_news",
            "source_name": "UN News 联合国新闻",
            "category": "国际组织",
            "country": "国际",
            "flag": "🌍",
            "color": "#009EDB",
            "title": "UNHCR: Global displaced persons reach historic 120 million",
            "summary": "The UN Refugee Agency reported that the number of people forcibly displaced worldwide has reached a new record, calling for increased international burden-sharing and funding for humanitarian operations.",
            "url": "https://news.un.org/en/story/unhcr-displaced-record",
            "published": (now - timedelta(hours=14)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # Global Times
        {
            "source_id": "globaltimes",
            "source_name": "Global Times 环球时报",
            "category": "官方媒体",
            "country": "中国",
            "flag": "🇨🇳",
            "color": "#B22222",
            "title": "China urges US to stop arm sales to Taiwan, calls for dialogue",
            "summary": "China's Foreign Ministry spokesperson reiterated Beijing's opposition to US arms sales to Taiwan, calling them a violation of the one-China principle and urging Washington to return to the path of dialogue.",
            "url": "https://www.globaltimes.cn/page/taiwan-arms-sales",
            "published": (now - timedelta(hours=4)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # NYT
        {
            "source_id": "nyt_world",
            "source_name": "New York Times 纽约时报",
            "category": "权威媒体",
            "country": "美国",
            "flag": "🇺🇸",
            "color": "#333333",
            "title": "Inside the AI race: How tech giants are betting on superintelligence",
            "summary": "A deep look at the escalating competition among major technology companies to develop increasingly powerful AI systems, and the regulatory challenges governments face in responding.",
            "url": "https://www.nytimes.com/2026/04/30/technology/ai-race",
            "published": (now - timedelta(hours=8)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # Guardian
        {
            "source_id": "guardian_world",
            "source_name": "The Guardian 卫报",
            "category": "权威媒体",
            "country": "英国",
            "flag": "🇬🇧",
            "color": "#052962",
            "title": "Plastic pollution treaty: Final negotiations fail to reach binding deal",
            "summary": "Talks to finalize an international treaty on plastic pollution broke down after key oil-producing nations blocked proposals for mandatory production caps, disappointing environmental campaigners.",
            "url": "https://www.theguardian.com/environment/plastic-treaty-collapse",
            "published": (now - timedelta(hours=16)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # VOA
        {
            "source_id": "voa_world",
            "source_name": "VOA 美国之音",
            "category": "官方媒体",
            "country": "美国",
            "flag": "🇺🇸",
            "color": "#1A5276",
            "title": "Washington announces new sanctions targeting North Korea's weapons program",
            "summary": "The US Treasury Department imposed new financial sanctions on entities linked to North Korea's ballistic missile and weapons development programs, in coordination with allied governments.",
            "url": "https://www.voanews.com/a/north-korea-sanctions",
            "published": (now - timedelta(hours=13)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
        # Sputnik
        {
            "source_id": "sputnik_world",
            "source_name": "Sputnik 卫星通讯社",
            "category": "官方媒体",
            "country": "俄罗斯",
            "flag": "🇷🇺",
            "color": "#0055A5",
            "title": "BRICS nations discuss expansion of non-dollar trade settlement system",
            "summary": "Finance ministers and central bank governors of BRICS member states held consultations on expanding the use of national currencies in bilateral trade, reducing dependence on the US dollar in international transactions.",
            "url": "https://sputnikglobe.com/world/brics-trade-currency",
            "published": (now - timedelta(hours=20)).isoformat(),
            "fetched_at": now.isoformat(),
            "source_type": "rss",
        },
    ]

    inserted = 0
    for article in demo_articles:
        if upsert_article(article):
            inserted += 1
    print(f"✓ 演示数据填充完成：插入 {inserted} 条文章")

if __name__ == "__main__":
    seed()
